name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.17

    - name: Build Docker image
      run: |
        docker build -t chaiwonhwang917/save-homez:${{ github.sha }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push chaiwonhwang917/save-homez:${{ github.sha }}

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Clean up Docker space: Remove all stopped containers, unused images and networks
          docker system prune -af
          # Optionally remove volumes not used by at least one container
          docker volume prune -f
          
          docker pull chaiwonhwang917/save-homez:${{ github.sha }}
          docker stop homez-ai || true
          docker rm homez-ai || true
          docker run -d --name homez-ai -p 80:5000 chaiwonhwang917/save-homez:${{ github.sha }}
